server:
  appName: go_web_test
  port: 8888

db:
  dsn: "root:mabang3.0@(192.168.2.44:3306)/swoole?charset=utf8mb4&parseTime=True&loc=Local"
  maxIdleConns: 200
  maxOpenConns: 1000
  connMaxLifetime: 60
redis:
  address: "redis-php-default.mabangerp.com:6379"
  index: 12
  password: Qf5k69t9RIW5A6htkptT
  idleTimeout: 12000
  maxIdle: 5
  maxActive: 20