server:
  appName: app
  port: 8888

datasource:
  primary: db
  datasource:
    db:
      dsn: "root:mabang3.0@(192.168.2.44:3306)/swoole?charset=utf8mb4&parseTime=True&loc=Local"
    db2:
      dsn: "root:mabang3.0@(192.168.2.44:3306)/swoole?charset=utf8mb4&parseTime=True&loc=Local"
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600

redis:
  address: "redis-php-default.mabangerp.com:6379"
  index: 12
  password: Qf5k69t9RIW5A6htkptT
  idleTimeout: 12000
  maxIdle: 5
  maxActive: 20