server.appName=app
server.port=8888

cloud.nacos.server-addr=http://dev-nacos.mabangerp.com
cloud.nacos.config.dataId=mas_arch_demo
cloud.nacos.config.namespace=eb133ea5-2987-47be-beac-03022efd6798
cloud.nacos.config.group=dev_erp_group
cloud.nacos.config.file-extension=properties
cloud.nacos.discovery.namespace=f9d028c7-dc77-46d8-b605-604610a2c4e3
cloud.nacos.discovery.group=dev_erp_group

