server.appName=app
server.port=8888
datasource.primary=db
datasource.datasource.db.dsn=root:mabang3.0@(192.168.2.44:3306)/swoole?charset=utf8mb4&parseTime=True&loc=Local
datasource.datasource.db2.dsn=root:mabang3.0@(192.168.2.44:3306)/swoole?charset=utf8mb4&parseTime=True&loc=Local
datasource.maxIdleConns=10
datasource.maxOpenConns=100
datasource.connMaxLifetime=3600


redis.php.address=redis-php-default.mabangerp.com:6379
redis.php.db=12
redis.php.password=Qf5k69t9RIW5A6htkptT
redis.php.idleTimeout=12000
redis.php.maxIdle=5
redis.php.poolSize=20

redis.java.address=redis-php-default.mabangerp.com:6379
redis.java.db=12
redis.java.password=Qf5k69t9RIW5A6htkptT
redis.java.idleTimeout=12000
redis.java.maxIdle=5
redis.java.poolSize=20


mongo.wishproduct.uri=mongodb-wish.mabangerp.com:27017,mongodb-wish1.mabangerp.com:27017
mongo.wishproduct.user=mabang
mongo.wishproduct.password=mabang123
mongo.wishproduct.replicaset=mongos
mongo.wishproduct.database=wishproduct
mongo.wishproduct.MaxConnIdleTime = 300
mongo.wishproduct.MaxPoolSize =20
mongo.wishproduct.MinPoolSize =5


mongo.wish.uri=mongodb-wish.mabangerp.com:27017,mongodb-wish1.mabangerp.com:27017
mongo.wish.user=mabang
mongo.wish.password=mabang123
mongo.wish.replicaset=mongos
mongo.wish.database=wishproduct
mongo.wish.MaxConnIdleTime = 300
mongo.wish.MaxPoolSize =20
mongo.wish.MinPoolSize =5